sudo ./peering openvpn down amsterdam01
sudo ./peering openvpn down clemson01
sudo ./peering openvpn down grnet01
sudo ./peering openvpn down isi01
sudo ./peering openvpn down neu01
sudo ./peering openvpn down phoenix01
sudo ./peering openvpn down seattle01
sudo ./peering openvpn down ufmg01
sudo ./peering openvpn down utah01
sudo ./peering openvpn down uw01
